### ISSUE TITLE
`makesheets` fails: RuntimeWarning: Setting unknown character attribute proficiencies_extra

### ISSUE THREAD

**Issue by jakewilliami** [michaelplews/DnD-character-sheets#1]
Hi there.  Firstly, I just wanted to say thank you for making this!  It looks really neat.

I am running `makesheets` as per the README:
```
$ makesheets
Processing io...done
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py:521: RuntimeWarning: Setting unknown character attribute proficiencies_extra
  RuntimeWarning)
Processing gunnloda...done
Processing inara...failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/makesheets", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/make_sheets.py", line 554, in main
    make_sheet(character_file=filename, flatten=(not args.editable), debug=args.debug)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/make_sheets.py", line 481, in make_sheet
    create_spellbook_pdf(character=character, basename=spellbook_base, keep_temp_files=debug)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/make_sheets.py", line 82, in create_spellbook_pdf
    return create_latex_pdf(character, basename, template, keep_temp_files=keep_temp_files)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/make_sheets.py", line 128, in create_latex_pdf
    raise exceptions.LatexError(f'Processing of {basename}.tex failed.'
dungeonsheets.exceptions.LatexError: Processing of inara_spellbook.tex failed. See inara_spellbook.log for details.
```

I am unsure if what follows is a result of the python error above or if it is the other way around.  If it is LaTeX that is initially throwing the error, then I suspect I might need to add `\DeclareUnicodeCharacter{0097}{ }` somewhere but I don't know where.  Have you had this error before?

```
$ cat inara_spellbook.log
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex 2020.4.28)  10 JUL 2020 00:19
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**inara_spellbook.tex
(/Users/jakeireland/git-workspace/DnD-character-sheets/inara_spellbook.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06>
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2019/12/20 v1.4l Standard LaTeX file (size option)
)
\c@part=\count167
\c@section=\count168
\c@subsection=\count169
\c@subsubsection=\count170
\c@paragraph=\count171
\c@subparagraph=\count172
\c@figure=\count173
\c@table=\count174
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen134
)
(/usr/local/texlive/2020/texmf-dist/tex/latex/geometry/geometry.sty
Package: geometry 2020/01/02 v5.9 Page Geometry

(/usr/local/texlive/2020/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks15
)
(/usr/local/texlive/2020/texmf-dist/tex/generic/iftex/ifvtex.sty
Package: ifvtex 2019/10/25 v1.7 ifvtex legacy package. Use iftex instead.

(/usr/local/texlive/2020/texmf-dist/tex/generic/iftex/iftex.sty
Package: iftex 2020/03/06 v1.0d TeX engine tests
))
\Gm@cnth=\count175
\Gm@cntv=\count176
\c@Gm@tempcnt=\count177
\Gm@bindingoffset=\dimen135
\Gm@wd@mp=\dimen136
\Gm@odd@mp=\dimen137
\Gm@even@mp=\dimen138
\Gm@layoutwidth=\dimen139
\Gm@layoutheight=\dimen140
\Gm@layouthoffset=\dimen141
\Gm@layoutvoffset=\dimen142
\Gm@dimlist=\toks16
)
(/usr/local/texlive/2020/texmf-dist/tex/latex/graphics/color.sty
Package: color 2019/11/23 v1.2a Standard LaTeX Color (DPC)

(/usr/local/texlive/2020/texmf-dist/tex/latex/graphics-cfg/color.cfg
File: color.cfg 2016/01/02 v1.6 sample color configuration
)
Package color Info: Driver file: pdftex.def on input line 147.

(/usr/local/texlive/2020/texmf-dist/tex/latex/graphics-def/pdftex.def
File: pdftex.def 2018/01/08 v1.0l Graphics/color driver for pdftex
)
(/usr/local/texlive/2020/texmf-dist/tex/latex/graphics/dvipsnam.def
File: dvipsnam.def 2016/06/17 v3.0m Driver-dependent file (DPC,SPQR)
))
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def
File: l3backend-pdfmode.def 2020-03-12 L3 backend support: PDF mode
\l__kernel_color_stack_int=\count178
\l__pdf_internal_box=\box45
)

LaTeX Warning: Unused global option(s):
    [lettersize].

(/Users/jakeireland/git-workspace/DnD-character-sheets/inara_spellbook.aux)
\openout1 = `inara_spellbook.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 12.
LaTeX Font Info:    ... okay on input line 12.

*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
*geometry* verbose mode - [ preamble ] result:
* driver: pdftex
* paper: <default>
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes:
* h-part:(L,W,R)=(42.67912pt, 528.93675pt, 42.67912pt)
* v-part:(T,H,B)=(42.67912pt, 709.61174pt, 42.67912pt)
* \paperwidth=614.295pt
* \paperheight=794.96999pt
* \textwidth=528.93675pt
* \textheight=709.61174pt
* \oddsidemargin=-29.59087pt
* \evensidemargin=-29.59087pt
* \topmargin=-66.59087pt
* \headheight=12.0pt
* \headsep=25.0pt
* \topskip=10.0pt
* \footskip=30.0pt
* \marginparwidth=4.0pt
* \marginparsep=10.0pt
* \columnsep=10.0pt
* \skip\footins=9.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumntrue
* \@twosidefalse
* \@mparswitchfalse
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)

(/usr/local/texlive/2020/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
\scratchcounter=\count179
\scratchdimen=\dimen143
\scratchbox=\box46
\nofMPsegments=\count180
\nofMParguments=\count181
\everyMPshowfont=\toks17
\MPscratchCnt=\count182
\MPscratchDim=\dimen144
\MPnumerator=\count183
\makeMPintoPDFobject=\count184
\everyMPtoPDFconversion=\toks18
)
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <12> on input line 14.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <8> on input line 14.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <6> on input line 14.
 [1{/usr/local/texlive/2020/texmf-var/fonts/map/pdftex/updmap/pdftex.map}


]

! Package inputenc Error: Unicode character  (U+0097)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.341 ...ith some other explanation for its fall
                                                  it was pushed, it
Here is how much of TeX's memory you used:
 1519 strings out of 480608
 22878 string characters out of 5903630
 270416 words of memory out of 5000000
 17448 multiletter control sequences out of 15000+600000
 536800 words of font info for 39 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 30i,8n,34p,200b,213s stack positions out of 5000i,500n,10000p,200000b,80000s

!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by canismarko** [comment]
Hi, @jakewilliami. Glad you like it.

Actually, this was just an invalid character instead of a hypen in the spell description in the underlying dungeonsheets package. Most of the spell descriptions were scraped from websites, and many of them have mistakes. I got rid of that character from all the spells that start with P, so hopefully it will work now if you pull the last the latest changes from https://github.com/canismarko/dungeon-sheets

I'm going to close this since I think it's fixed, but feel free to re-open it if it doesn't work.

Fix: [51c5e8132231411f647f65b15e0407731f374ee0](https://github.com/canismarko/dungeon-sheets/commit/51c5e8132231411f647f65b15e0407731f374ee0)
